spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:tcp://localhost/~/datajpa
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace